# Generated by Django 2.1.5 on 2019-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('link', models.CharField(max_length=500)),
                ('time_added', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Headlines',
            },
        ),
    ]
