# Generated by Django 2.1.5 on 2019-01-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlines',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
